added Ciclos to Project
Isa-30a/Compilador pull request #10
Opened 2024-06-12 17:24 UTC by JorgeDSierra

Se realizó la función de transformar pseudocódigo a C++ para las funciones de Ciclos como lo son, ciclo FOR. WHILE y Do WHILE,
Este programa recibe un archivo txt  donde se tiene el pseudocódigo con palabras reservadas, por ejemplo este formato que contiene todos los ciclos:

# Entrada:

```
PARA (ENTERO i = 0; i < 3; i++) HACER:
    IMPRIMIR "Valor de i: " i
    MIENTRAS (ENTERO j = 0; j < 2; j++) HACER:
        IMPRIMIR "Valor de j: " j
        REPETIR:
            IMPRIMIR "Dentro de Hacer-Mientras, k = " k
            k = k + 1
        MIENTRAS (k < 1)
        PARA (ENTERO l = 0; l < 2; l++) HACER:
            IMPRIMIR "Valor de l: " l
            MIENTRAS (ENTERO m = 0; m < 1; m++) HACER:
                IMPRIMIR "Valor de m: " m
                REPETIR:
                    IMPRIMIR "Dentro de Hacer-Mientras, n = " n
                    n = n + 1
                MIENTRAS (n < 1)
            FIN MIENTRAS
        FIN PARA
    FIN MIENTRAS
FIN PARA

```

# Salida:

```
for (ENTERO i = 0; i < 3; i++) {
    IMPRIMIR "Valor de i: " i
    while (ENTERO j = 0; j < 2; j++) {
        IMPRIMIR "Valor de j: " j
        do {
            IMPRIMIR "Dentro de Hacer-Mientras, k = " k
            k = k + 1
        } while (k < 1);
        for (ENTERO l = 0; l < 2; l++) {
            IMPRIMIR "Valor de l: " l
            while (ENTERO m = 0; m < 1; m++) {
                IMPRIMIR "Valor de m: " m
                do {
                    IMPRIMIR "Dentro de Hacer-Mientras, n = " n
                    n = n + 1
                } while (n < 1);
            }
        }
    }
}
```

2024-06-12 22:32 UTC, Isa-30a commented on src/main/java/ciclos/PseudocodeConverter.java
> +        Matcher matcher = pattern.matcher(pseudocode);
cambiar estructura de la expresion regular, para que encaje con formato establecido

2024-06-12 22:34 UTC, Isa-30a commented on src/main/java/ciclos/PseudocodeConverter.java
> +        Pattern pattern = Pattern.compile("(?s)MIENTRAS\\s*\\(([^\\)]+)\\)\\s*HACER:\\s*(.*?)\\s*FIN MIENTRAS");
Quitar parentesis del MIENTRAS para que encaje con formato establecido

2024-06-12 22:35 UTC, Isa-30a commented on src/main/java/ciclos/PseudocodeConverter.java
> +        Pattern pattern = Pattern.compile("(?s)REPETIR:\\s*(.*?)\\s*MIENTRAS\\s*\\(([^\\)]+)\\)");
Quitar parentesis de la expresion para que encaje con formato establecido

2024-06-13 03:55 UTC, kaponeminusone commented on src/main/java/ciclos/PseudocodeConverter.java
> +    //PROTEJEMOS EL TEXTO ENTRE COMILLAS EN CASO DE HABER UNA PALABRA RESERVADA
PROTEGEMOS

2024-06-13 03:55 UTC, kaponeminusone commented on src/main/java/ciclos/PseudocodeConverter.java
> +//DESARROLLADO POR JORGE DAVID SIERRA VEGA
no son 4?

2024-06-13 03:59 UTC, Moya004 requested changes

2024-06-13 03:59 UTC, Moya004 commented on src/main/java/ciclos/PseudocodeConverter.java
> +
refactorizar en clases con responsabilidades  especificas

2024-06-13 04:14 UTC, Isa-30a approved these changes

2024-06-13 04:14 UTC, Moya004 approved these changes

2024-06-13 04:15 UTC, merged